/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'doc',
      id: '总目录',
    },
    {
    type: 'category',
      label: '玩家手册',
      items: [
        {
          type: 'doc',
          id: '基础教程',
        },
        {
          type: 'doc',
          id: '世界设置详解',
        },
        {
          type: 'doc',
          id: '刷新范围，现实气泡',
        },
        {
          type: 'doc',
          id: '常见问题 Q&A',
        },
        {
          type: 'category',
          label: '小@的状态',
          items: [
            {
              type: 'doc',
              id: '属性的影响',
            },
            {
              type: 'doc',
              id: '健身·心肺运动',
            },
            {
              type: 'doc',
              id: '疼痛与止痛药',
            },
            {
              type: 'doc',
              id: '速度与移动耗时',
            },
            {
              type: 'doc',
              id: '正负面状态详解',
            },
            {
              type: 'doc',
              id: '常见疾病诊治方法',
            },
          ],
        },
        {
          type: 'doc',
          id: '技能与专长',
        },
        {
          type: 'doc',
          id: '特性解释及评价',
        },
        {
          type: 'doc',
          id: '怪物机制',
        },
        {
          type: 'category',
          label: '攻击与防御',
          link: {type: 'doc', id: '攻击与防御'},
          items: [
            {
              type: 'doc',
              id: '武术流派详解',
            },
            {
              type: 'doc',
              id: '基础战术准则',
            },

          ],
        },
        {
          type: 'category',
          label: 'CBM/变异',
          items: [
            {
              type: 'doc',
              id: 'CBM体系与功能详解',
            },
            {
              type: 'doc',
              id: '变异体系与路线详解',
            },
          ],
        },
        {
          type: 'doc',
          id: 'NPC与任务流程',
        },
        {
          type: 'doc',
          id: '食物获取与储存',
        },
        {
          type: 'doc',
          id: '载具机制',
        },
        {
          type: 'doc',
          id: '实验版家电系统',
        },
        {
          type: 'doc',
          id: '空间风暴事件',
        },

        {
          type: 'doc',
          id: '地点概述与探索建议',
        },
        {
          type: 'doc',
          id: '神器系统详细解释',
        },
      ],
    },
        {
    type: 'category',
      label: '开发者手册',
      items: [
        {
         type: 'autogenerated',
         dirName: 'content', //
        },
      ],
    },

    {
      type: 'doc',
      id: '往期更新记录',
    }
  ]
   // '总目录',
   // ''
   // {type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
